//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.GuestPlayerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestPlayerService.IGuestPlayerService")]
    public interface IGuestPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayerResponse")]
        Service.Results.OperationResponse RegisterGuestPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/RegisterGuestPlayerResponse")]
        System.Threading.Tasks.Task<Service.Results.OperationResponse> RegisterGuestPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayerResponse")]
        Service.Results.OperationResponse LogoutGuestPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayer", ReplyAction="http://tempuri.org/IGuestPlayerService/LogoutGuestPlayerResponse")]
        System.Threading.Tasks.Task<Service.Results.OperationResponse> LogoutGuestPlayerAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestPlayerServiceChannel : ServiceTest.GuestPlayerService.IGuestPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestPlayerServiceClient : System.ServiceModel.ClientBase<ServiceTest.GuestPlayerService.IGuestPlayerService>, ServiceTest.GuestPlayerService.IGuestPlayerService {
        
        public GuestPlayerServiceClient() {
        }
        
        public GuestPlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestPlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestPlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestPlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Service.Results.OperationResponse RegisterGuestPlayer(string username) {
            return base.Channel.RegisterGuestPlayer(username);
        }
        
        public System.Threading.Tasks.Task<Service.Results.OperationResponse> RegisterGuestPlayerAsync(string username) {
            return base.Channel.RegisterGuestPlayerAsync(username);
        }
        
        public Service.Results.OperationResponse LogoutGuestPlayer(string username) {
            return base.Channel.LogoutGuestPlayer(username);
        }
        
        public System.Threading.Tasks.Task<Service.Results.OperationResponse> LogoutGuestPlayerAsync(string username) {
            return base.Channel.LogoutGuestPlayerAsync(username);
        }
    }
}
