//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestPlayers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuestPlayers()
        {
            this.LobbyPlayers = new HashSet<LobbyPlayers>();
        }
    
        public int GuestID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual StatusPlayer StatusPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LobbyPlayers> LobbyPlayers { get; set; }
    }
}
