//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LobbyPlayers
    {
        public int LobbyID { get; set; }
        public int PlayerID { get; set; }
        public int GuestID { get; set; }
        public string PlayerStatus { get; set; }
    
        public virtual GameLobby GameLobby { get; set; }
        public virtual GuestPlayers GuestPlayers { get; set; }
        public virtual Player Player { get; set; }
    }
}
