//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public int PlayerID { get; set; }
        public string FullName { get; set; }
        public string AvatarURL { get; set; }
        public string Bio { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> SignUpDate { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual StatusPlayer StatusPlayer { get; set; }
    }
}
